### ISSUE TITLE
移动端首页文章卡片显示错误

### ISSUE THREAD

**Issue by KARPED1EM** [NCSIMON/NCSIMON.github.io#6]
![Screenshot_2022-12-01-19-45-38-450_com.android.chrome.jpg](https://user-images.githubusercontent.com/89320463/205044948-37d65cd0-b3e9-4cb3-b4b3-8e8a9aca8cf9.jpg)

**Comment by ZYKAK** [comment]
额

**Comment by ZYKAK** [comment]
感谢来自KARPED1EM的温馨提醒，此问题已解决。（╯‵□′）╯︵┴─┴

**Comment by ZYKAK** [comment]
喜喜

**Comment by KARPED1EM** [comment]
你这哪里是解决问题，你这是解决了出现问题的部分。(╬ﾟдﾟ)╭∩╮
